version: "3.7"

services:
  todos:
    build:
       context: .
       target: server
    ports:
      - "50051:50051"
  client:
    build:
      context: .
      target: client
    environment:
      BACKEND: "todos:50051"
    restart: always
  todos-gw:
    build:
      context: gen/grpc-gateway
    environment:
      TODOS_BACKEND: "todos:50051"
      TODOS_CORS_ALLOW-ORIGIN: "*"
      TODOS_CORS_ALLOW-METHODS: "GET, OPTIONS, DELETE, POST"
    ports:
      - "8080:80"
  todos-graphql:
    build:
      context: todos-graphql
    ports:
      - "8000:8000"


networks:
  default:
    name: grpc-example

