apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: todos-server
   labels:
      app: todos
      tier: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: todos
        tier: server
    spec:
      containers:
      - name: todos-server
        image: gcr.io/grpc-demo-1/todos-server
        imagePullPolicy: Always
        ports:
        - name: todos-server
          containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: todos-server
spec:
  selector:
    app: todos
    tier: server
  ports:
  - port: 50051
    targetPort: todos-server
