apiVersion: apps/v1
kind: Deployment
metadata:
   name: todos-server
   namespace: todos
   labels:
      app: todos
      tier: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos
      tier: server
  template:
    metadata:
      labels:
        app: todos
        tier: server
    spec:
      containers:
      - name: todos-server
        image: gcr.io/todos/todos-server
        ports:
        - name: todos-server
          containerPort: 50052
        resources:
          requests:
            cpu: 100m
            memory: 128M
          limits:
            cpu: 200m
            memory:  256M
---
apiVersion: v1
kind: Service
metadata:
  name: todos-server
  namespace: todos
spec:
  selector:
    app: todos
    tier: server
  ports:
  - name: todos-server
    port: 50052
    targetPort: todos-server
---

# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: todos-ingress
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /todos
#         backend:
#           serviceName: todos-server
#           servicePort: 8080
#       - path: /*
#         backend:
#           serviceName: todos-server
#           servicePort: 8080
