apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: todos-server
   labels:
      app: todos
      tier: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: todos
        tier: server
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http2_port=9000",
          "--http_port=8080",
          "--service=todos.endpoints.grpc-demo-1.cloud.goog",
          "--rollout_strategy=managed",
          "--backend=grpc://127.0.0.1:50051",
          "-z", "healthz"
          ]
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        ports:
        - name: esp
          containerPort: 9000
        - name: esp-http
          containerPort: 8080
      - name: todos-server
        image: gcr.io/grpc-demo-1/todos-server
        imagePullPolicy: Always
        ports:
        - name: todos-server
          containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: todos-server
spec:
  selector:
    app: todos
    tier: server
  ports:
  - name: todos-server
    port: 50051
    targetPort: todos-server
  - name: esp
    port: 9000
    targetPort: esp
  - name: http
    port: 8080
    targetPort: esp-http
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: todos-esp
spec:
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http2
  selector:
    app: todos
    tier: server
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: todos-esp-http
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: todos
    tier: server
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todos-ingress
spec:
  rules:
  - http:
      paths:
      - path: /todos
        backend:
          serviceName: todos-server
          servicePort: 8080
      - path: /*
        backend:
          serviceName: todos-server
          servicePort: 8080
