apiVersion: apps/v1
kind: Deployment
metadata:
   name: todos-client
   namespace: todos
   labels:
      app: todos
      tier: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos
      tier: client
  template:
    metadata:
      labels:
        app: todos
        tier: client
    spec:
      containers:
      - name: todos-client
        image: gcr.io/todos/todos-client
        env:
          - name: BACKEND
            value: "todos-server:50052"
