type: google.api.Service
config_version: 3

name: todos.endpoints.grpc-demo-1.cloud.goog

title: Todos gRPC API
apis:
  - name: todos.Todos

endpoints:
  - name: todos.endpoints.grpc-demo-1.cloud.goog
    target: "35.237.176.243"

usage:
  rules:
    - selector: "*"
      allow_unregistered_calls: true

